# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mycalc.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_calc(object):
    def setupUi(self, calc):
        calc.setObjectName("calc")
        calc.resize(292, 287)
        self.centralwidget = QtWidgets.QWidget(calc)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 130, 231, 111))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pdeduct = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pdeduct.setObjectName("pdeduct")
        self.gridLayout.addWidget(self.pdeduct, 3, 4, 1, 1)
        self.p5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.p5.setObjectName("p5")
        self.gridLayout.addWidget(self.p5, 1, 2, 1, 1)
        self.p6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.p6.setObjectName("p6")
        self.gridLayout.addWidget(self.p6, 1, 3, 1, 1)
        self.p7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.p7.setObjectName("p7")
        self.gridLayout.addWidget(self.p7, 0, 1, 1, 1)
        self.p9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.p9.setObjectName("p9")
        self.gridLayout.addWidget(self.p9, 0, 3, 1, 1)
        self.p8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.p8.setObjectName("p8")
        self.gridLayout.addWidget(self.p8, 0, 2, 1, 1)
        self.pmultiply = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pmultiply.setObjectName("pmultiply")
        self.gridLayout.addWidget(self.pmultiply, 1, 4, 1, 1)
        self.ppunto = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ppunto.setObjectName("ppunto")
        self.gridLayout.addWidget(self.ppunto, 5, 2, 1, 1)
        self.pdivide = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pdivide.setObjectName("pdivide")
        self.gridLayout.addWidget(self.pdivide, 0, 4, 1, 1)
        self.p3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.p3.setObjectName("p3")
        self.gridLayout.addWidget(self.p3, 3, 3, 1, 1)
        self.psum = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.psum.setObjectName("psum")
        self.gridLayout.addWidget(self.psum, 5, 4, 1, 1)
        self.pperc = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pperc.setObjectName("pperc")
        self.gridLayout.addWidget(self.pperc, 5, 3, 1, 1)
        self.p0 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.p0.setObjectName("p0")
        self.gridLayout.addWidget(self.p0, 5, 1, 1, 1)
        self.p1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.p1.setObjectName("p1")
        self.gridLayout.addWidget(self.p1, 3, 1, 1, 1)
        self.p4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.p4.setObjectName("p4")
        self.gridLayout.addWidget(self.p4, 1, 1, 1, 1)
        self.p2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.p2.setObjectName("p2")
        self.gridLayout.addWidget(self.p2, 3, 2, 1, 1)
        self.pequal = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pequal.setObjectName("pequal")
        self.gridLayout.addWidget(self.pequal, 5, 5, 1, 1)
        self.pcancel = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pcancel.setObjectName("pcancel")
        self.gridLayout.addWidget(self.pcancel, 3, 5, 1, 1)
        self.pbackwards = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pbackwards.setObjectName("pbackwards")
        self.gridLayout.addWidget(self.pbackwards, 1, 5, 1, 1)
        self.ponoff = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ponoff.setFont(font)
        self.ponoff.setObjectName("ponoff")
        self.gridLayout.addWidget(self.ponoff, 0, 5, 1, 1)
        self.screen = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.screen.setGeometry(QtCore.QRect(30, 9, 231, 111))
        self.screen.setObjectName("screen")
        calc.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(calc)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 292, 22))
        self.menubar.setObjectName("menubar")
        calc.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(calc)
        self.statusbar.setObjectName("statusbar")
        self.btn=[self.p0,self.p1,self.p2,self.p3,self.p4,self.p5,self.p6,self.p7,self.p8,self.p9]
        self.o=[self.psum,self.pdeduct,self.pmultiply,self.pdivide,self.pbackwards,self.pequal,self.ppunto,self.pcancel,self.screen]

        calc.setStatusBar(self.statusbar)

        self.retranslateUi(calc)
        QtCore.QMetaObject.connectSlotsByName(calc)

    def retranslateUi(self, calc):
        _translate = QtCore.QCoreApplication.translate
        calc.setWindowTitle(_translate("calc", "Pie Calculator"))
        self.pdeduct.setText(_translate("calc", "-"))
        self.p5.setText(_translate("calc", "5"))
        self.p6.setText(_translate("calc", "6"))
        self.p7.setText(_translate("calc", "7"))
        self.p9.setText(_translate("calc", "9"))
        self.p8.setText(_translate("calc", "8"))
        self.pmultiply.setText(_translate("calc", "X"))
        self.ppunto.setText(_translate("calc", "."))
        self.pdivide.setText(_translate("calc", "/"))
        self.p3.setText(_translate("calc", "3"))
        self.psum.setText(_translate("calc", "+"))
        self.pperc.setText(_translate("calc", "%"))
        self.p0.setText(_translate("calc", "0"))
        self.p1.setText(_translate("calc", "1"))
        self.p4.setText(_translate("calc", "4"))
        self.p2.setText(_translate("calc", "2"))
        self.pequal.setText(_translate("calc", "="))
        self.pcancel.setText(_translate("calc", "C"))
        self.pbackwards.setText(_translate("calc", "<-"))
        self.ponoff.setText(_translate("calc", "OFF"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    calc = QtWidgets.QMainWindow()
    ui = Ui_calc()
    ui.setupUi(calc)
    calc.show()
    sys.exit(app.exec_())

